### ISSUE TITLE
discord 2.0

### ISSUE THREAD

**Issue by ghost** [IshanKamboj/Giveaway-Bot#1]
How oculd get this working on 2.0, in gend async generator object has no attribute flatten:

discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'async_generator' object has no attribute 'flatten'
